version: '3.8'

services:
  api:
    build: .
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - image_uploads:/app/uploads
      - sqlite_data:/app/data
    env_file:
      - .env.production
    environment:
      - SQLITE_DB=/app/data/image_processing.db
      - UPLOAD_DIR=/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

volumes:
  image_uploads:
    driver: local
  sqlite_data:
    driver: local 