version: '3.8'

services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - image_uploads:/app/uploads
      - sqlite_data:/app/data
    environment:
      - SQLITE_DB=/app/data/image_processing.db
      - UPLOAD_DIR=/app/uploads
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3

volumes:
  image_uploads:
  sqlite_data:

networks:
  app-network:
    driver: bridge 